/**
 * Module: Stack Health Auth
 *
 * Responsibility:
 * - Build the correct read-only Portainer authentication headers.
 * - Keep token handling in one place so clients never print or transform secrets.
 *
 * Notes:
 * - Part of LENSINFRA oclif CLI.
 * - Do not change runtime behavior.
 */

import { IAppConfig } from "./types.js";

/**
 * Returns the header shape required by the selected Portainer authentication mode.
 */
export function fnPortainerAuthHeaders(iConfig: IAppConfig): Record<string, string> {
  // Decision: Bearer mode is for JWT tokens generated by Portainer login.
  if (iConfig.portainerAuthMode === "bearer") {
    // Output: JWT authentication header for Portainer environments that require Bearer auth.
    return {
      Authorization: `Bearer ${iConfig.portainerPatToken}`
    };
  }

  // Output: API access token authentication header for Portainer PAT tokens.
  return {
    "X-API-Key": iConfig.portainerPatToken
  };
}
